# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Tarea6'
        db.create_table('LaLibretaDelDetective_tarea6', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('alumno', self.gf('django.db.models.fields.CharField')(max_length=50, default='NONE')),
            ('t6_1', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t6_2', self.gf('django.db.models.fields.CharField')(max_length=1200, blank=True, null=True, default='')),
        ))
        db.send_create_signal('LaLibretaDelDetective', ['Tarea6'])

        # Adding model 'Tarea4'
        db.create_table('LaLibretaDelDetective_tarea4', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('alumno', self.gf('django.db.models.fields.CharField')(max_length=50, default='NONE')),
            ('t4_1_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_1_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_1_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_1_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_1_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_1_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_1_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_1_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_1_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_1_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_2_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_2_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_2_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_2_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_2_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_2_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_2_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_2_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_2_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_2_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_3_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_3_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_3_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_3_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_3_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_3_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_3_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_3_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_3_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_3_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_4_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_4_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_4_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_4_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_4_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_4_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_4_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_4_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_4_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_4_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_5_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_5_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_5_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_5_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_5_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_5_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_5_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_5_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_5_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_5_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_6_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_6_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_6_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_6_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_6_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_6_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_6_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_6_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_6_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_6_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_7_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_7_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_7_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_7_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_7_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_7_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_7_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_7_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_7_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_7_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_8_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_8_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_8_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_8_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_8_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_8_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_8_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_8_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_8_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_8_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_9_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_9_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_9_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_9_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_9_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_9_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_9_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_9_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_9_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_9_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_10_1', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_10_2', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_10_3', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_10_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_10_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_10_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t4_10_7', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_10_8', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_10_9', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
            ('t4_10_10', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True, null=True, default='')),
        ))
        db.send_create_signal('LaLibretaDelDetective', ['Tarea4'])

        # Adding model 'Alumno'
        db.create_table('LaLibretaDelDetective_alumno', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('alumno', self.gf('django.db.models.fields.CharField')(max_length=50, default='NONE')),
        ))
        db.send_create_signal('LaLibretaDelDetective', ['Alumno'])

        # Adding model 'Tarea2'
        db.create_table('LaLibretaDelDetective_tarea2', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('alumno', self.gf('django.db.models.fields.CharField')(max_length=50, default='NONE')),
            ('t2_1', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_2', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_3', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_7', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_8', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_9', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t2_10', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
        ))
        db.send_create_signal('LaLibretaDelDetective', ['Tarea2'])

        # Adding model 'Tarea3'
        db.create_table('LaLibretaDelDetective_tarea3', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('alumno', self.gf('django.db.models.fields.CharField')(max_length=50, default='NONE')),
            ('t3_1', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_2', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_3', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_4', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_5', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_6', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_7', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_8', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_9', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_10', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_11', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_12', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_13', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_14', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_15', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_16', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_17', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_18', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_19', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_20', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_21', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_22', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_23', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_24', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_25', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_26', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_27', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_28', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_29', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
            ('t3_30', self.gf('django.db.models.fields.CharField')(max_length=300, blank=True, null=True, default='')),
        ))
        db.send_create_signal('LaLibretaDelDetective', ['Tarea3'])

        # Adding model 'Tarea5'
        db.create_table('LaLibretaDelDetective_tarea5', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('alumno', self.gf('django.db.models.fields.CharField')(max_length=50, default='NONE')),
            ('t5_1', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_2', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_3', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_4', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_5', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_6', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_7', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_8', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_9', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
            ('t5_10', self.gf('django.db.models.fields.CharField')(max_length=800, blank=True, null=True, default='')),
        ))
        db.send_create_signal('LaLibretaDelDetective', ['Tarea5'])


        # Changing field 'Tarea1.alumno'
        db.alter_column('LaLibretaDelDetective_tarea1', 'alumno', self.gf('django.db.models.fields.CharField')(max_length=50))

    def backwards(self, orm):
        # Deleting model 'Tarea6'
        db.delete_table('LaLibretaDelDetective_tarea6')

        # Deleting model 'Tarea4'
        db.delete_table('LaLibretaDelDetective_tarea4')

        # Deleting model 'Alumno'
        db.delete_table('LaLibretaDelDetective_alumno')

        # Deleting model 'Tarea2'
        db.delete_table('LaLibretaDelDetective_tarea2')

        # Deleting model 'Tarea3'
        db.delete_table('LaLibretaDelDetective_tarea3')

        # Deleting model 'Tarea5'
        db.delete_table('LaLibretaDelDetective_tarea5')


        # Changing field 'Tarea1.alumno'
        db.alter_column('LaLibretaDelDetective_tarea1', 'alumno', self.gf('django.db.models.fields.CharField')(null=True, max_length=15))

    models = {
        'LaLibretaDelDetective.alumno': {
            'Meta': {'object_name': 'Alumno'},
            'alumno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'default': "'NONE'"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'LaLibretaDelDetective.tarea1': {
            'Meta': {'object_name': 'Tarea1'},
            'alumno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'default': "'NONE'"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            't1a_1': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_10': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_11': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_12': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_13': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_14': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_15': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_2': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_3': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_4': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_5': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_6': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_7': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_8': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1a_9': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True', 'null': 'True', 'default': "'-'"}),
            't1b_1_1': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_1_2': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_1_3': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_1_4': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_1_5': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_2_1': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_2_2': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_2_3': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_2_4': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_2_5': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_3_1': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_3_2': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_3_3': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_3_4': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't1b_3_5': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True', 'null': 'True', 'default': "''"})
        },
        'LaLibretaDelDetective.tarea2': {
            'Meta': {'object_name': 'Tarea2'},
            'alumno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'default': "'NONE'"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            't2_1': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_10': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_2': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_3': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_7': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_8': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't2_9': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"})
        },
        'LaLibretaDelDetective.tarea3': {
            'Meta': {'object_name': 'Tarea3'},
            'alumno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'default': "'NONE'"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            't3_1': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_10': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_11': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_12': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_13': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_14': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_15': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_16': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_17': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_18': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_19': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_2': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_20': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_21': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_22': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_23': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_24': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_25': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_26': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_27': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_28': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_29': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_3': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_30': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_7': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_8': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't3_9': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"})
        },
        'LaLibretaDelDetective.tarea4': {
            'Meta': {'object_name': 'Tarea4'},
            'alumno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'default': "'NONE'"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            't4_10_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_10_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_1_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_2_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_3_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_4_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_5_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_6_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_7_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_8_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_1': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_10': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_2': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_3': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_4': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_5': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_6': ('django.db.models.fields.CharField', [], {'max_length': '300', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_7': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_8': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't4_9_9': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True', 'null': 'True', 'default': "''"})
        },
        'LaLibretaDelDetective.tarea5': {
            'Meta': {'object_name': 'Tarea5'},
            'alumno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'default': "'NONE'"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            't5_1': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_10': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_2': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_3': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_4': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_5': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_6': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_7': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_8': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't5_9': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"})
        },
        'LaLibretaDelDetective.tarea6': {
            'Meta': {'object_name': 'Tarea6'},
            'alumno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'default': "'NONE'"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            't6_1': ('django.db.models.fields.CharField', [], {'max_length': '800', 'blank': 'True', 'null': 'True', 'default': "''"}),
            't6_2': ('django.db.models.fields.CharField', [], {'max_length': '1200', 'blank': 'True', 'null': 'True', 'default': "''"})
        }
    }

    complete_apps = ['LaLibretaDelDetective']